# Generated by Django 4.1.7 on 2023-03-08 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_materials_itemmaterials_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='default',
        ),
        migrations.DeleteModel(
            name='Pattern',
        ),
    ]
