# Generated by Django 4.1.7 on 2023-03-08 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_part_default_delete_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='default',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='main.material'),
        ),
    ]
