# Generated by Django 4.1.7 on 2023-03-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_part_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='bumpmap',
            field=models.FileField(blank=True, null=True, upload_to='bumpmaps'),
        ),
    ]
