# Generated by Django 4.1.7 on 2023-03-11 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_material_bumpmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='bumpmap',
            field=models.ImageField(blank=True, null=True, upload_to='bumpmaps'),
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=10)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='textures')),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('shininess', models.FloatField(default=300)),
                ('texture', models.ImageField(blank=True, null=True, upload_to='textures')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='main.material')),
            ],
        ),
        migrations.AlterField(
            model_name='part',
            name='default',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='main.pattern'),
        ),
    ]
